# Generated by Django 5.2.3 on 2025-07-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tercer_entrega_app', '0003_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='bandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('aniodeformacion', models.CharField(max_length=4)),
                ('pais', models.CharField(max_length=50)),
                ('historia', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='recitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banda', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
