# Generated by Django 5.2.3 on 2025-07-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tercer_entrega_app', '0004_bandas_recitales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bandas',
            new_name='Banda',
        ),
        migrations.RenameModel(
            old_name='recitales',
            new_name='Recital',
        ),
    ]
